<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/servers/McpServices.Index/McpServices.Index.csproj" />
    <ProjectReference Include="../McpServices.TestSupport/McpServices.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" />
  </ItemGroup>

</Project>
